import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('192.168.31.93', username='man', password='giao666666', timeout=10)
stdin, stdout, stderr = ssh.exec_command("grep -c '_fmt' /home/man/pi_stream_puzzle.py")
print('_fmt:', stdout.read().decode().strip())
stdin, stdout, stderr = ssh.exec_command("grep 'Solve OK' /tmp/puzzle.log | tail -3")
print('Solves:', stdout.read().decode().strip())
stdin, stdout, stderr = ssh.exec_command("grep 'Solve FAILED' /tmp/puzzle.log | tail -3")
print('Failures:', stdout.read().decode().strip())
ssh.close()
